source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'CYPasswordViewDemo' do
  use_frameworks!

  pod 'PasswordBoxView', '~> 0.0.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.2'
      end
  end
end
